// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class AvailableBet
{
    public int AvailableBetId { get; set; }

    public int RaceParticipantId { get; set; }

    public int BetTypeId { get; set; }

    public decimal Odds { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public bool? IsSuccess { get; set; }

    public virtual BetType BetType { get; set; }

    public virtual RaceParticipant RaceParticipant { get; set; }

    public virtual ICollection<TicketBet> TicketBets { get; set; } = new List<TicketBet>();
}