// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class BetType
{
    public int BetTypeId { get; set; }

    public string BetTypeDesc { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public virtual ICollection<AvailableBet> AvailableBets { get; set; } = new List<AvailableBet>();
}