// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DogTrack.DataAccess.DogTrackDataAccess.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities
{
    public partial interface IXSdbContextProcedures
    {
        Task<int> InsertRacesAsync(int? numberOfRaces, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateAvailableBetSuccessStatusAsync(int? raceId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateLostTicketsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> ValidateTicketsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
