// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class RaceParticipant
{
    public int RaceParticipantId { get; set; }

    public int RaceId { get; set; }

    public int ParticipantId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public virtual ICollection<AvailableBet> AvailableBets { get; set; } = new List<AvailableBet>();

    public virtual Participant Participant { get; set; }

    public virtual Race Race { get; set; }
}