// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class Race
{
    public int RaceId { get; set; }

    public string Name { get; set; }

    public DateTime? RaceStart { get; set; }

    public int? RaceWinnerId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public virtual ICollection<RaceParticipant> RaceParticipants { get; set; } = new List<RaceParticipant>();
}