// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class Ticket
{
    public int TicketId { get; set; }

    public int TicketStatusId { get; set; }

    public int UserId { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public decimal? WinAmount { get; set; }

    public decimal BetAmount { get; set; }

    public virtual ICollection<TicketBet> TicketBets { get; set; } = new List<TicketBet>();
}