// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class TicketBet
{
    public int TicketBetId { get; set; }

    public int AvailableBetId { get; set; }

    public int TicketId { get; set; }

    public decimal Odds { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpd { get; set; }

    public string LastUpdBy { get; set; }

    public virtual AvailableBet AvailableBet { get; set; }

    public virtual Ticket Ticket { get; set; }
}