// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DogTrack.DataAccess.DogTrackDataAccess.Entities;

public partial class WonTicket
{
    public int TicketId { get; set; }

    public decimal? WinAmount { get; set; }

    public int UserId { get; set; }
}